#!/bin/sh
die () {
    echo >&2 "$@"
    exit 1
}

[ "$#" -eq 1 ] || die "1 argument required, $# provided"
echo $1 | grep -E -q '^[0-9]+$' || die "Numeric argument required, "$1" provided"

AMOUNT=$1

spl-token accounts
spl-token transfer FidHzAe6A1mvjyX3Y9rSZTsp76bGhL7ii9UpdNiJ92Fm "$AMOUNT" A7qLewAaN5R7meAcr7fK9gzP1pJY7i1h8sc1WLSphVyD
